export const actions = {
  profile: {
    DATA_FETCHING: "PROFILE_DATA_FETCHING",
    DATA_FETCHED: "PROFILE_DATA_FETCHED",
    DATA_FETCH_ERROR: "PROFILE_DATA_FETCH_ERROR",
    USER_DATA_EDITED: "PROFILE_USER_DATA_UPDATED",
    IMAGE_UPDATED: "PROFILE IMAGE_DATA_UPDATED",
  },
  post: {
    DATA_FETCHING: "POST_DATA_FETCHING",
    DATA_FETCHED: "POST_DATA_FETCHED",
    DATA_FETCH_ERROR: "POST_DATA_FETCH_ERROR",
    USER_DATA_EDITED: "POST_USER_DATA_EDITED",
    USER_DATA_DELETED: "POST_USER_DATA_DELETED",
    USER_DATA_LIKED: "POST_USER_DATA_LIKED",
    USER_DATA_COMMENTED: "POST_USER_DATA_COMMENTED",
  },
};
